// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
// Location actions
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const DELETE_LOCATION_OPTIMISTIC = 'DELETE_LOCATION_OPTIMISTIC';
// Company actions
export const LOAD_COMPANY_SUCCESS = 'LOAD_COMPANY_SUCCESS';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const DELETE_COMPANY_OPTIMISTIC = 'DELETE_COMPANY_OPTIMISTIC';
// User actions
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USERS_OPTIMISTIC = 'DELETE_USERS_OPTIMISTIC';
export const ACTIVATE_USERS_OPTIMISTIC = 'ACTIVATE_USERS_OPTIMISTIC';
// Template actions
export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const EDIT_TEMPLATE_SUCCESS = 'EDIT_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_OPTIMISTIC = 'DELETE_TEMPLATE_OPTIMISTIC';
export const ASSIGN_MEALS_SUCCESS = 'ASSIGN_MEALS_SUCCESS';
//Meal actions
export const LOAD_MEALS_SUCCESS = 'LOAD_MEALS_SUCCESS';
export const CREATE_MEAL_SUCCESS = 'CREATE_MEAL_SUCCESS';
export const DELETE_MEALS_OPTIMISTIC = 'DELETE_MEALS_OPTIMISTIC';
export const UPDATE_MEALS_IS_ACTIVE = 'UPDATE_MEALS_IS_ACTIVE';
export const EDIT_MEAL_SUCCESS = 'EDIT_MEAL_SUCCESS';
//Order actions
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
